from enum import Enum


class UserRole(str, Enum):
    CANDIDATE = "candidate"
    RECRUITER = "recruiter"
    ADMIN = "admin"


class InterviewStage(str, Enum):
    INTRO = "INTRO"
    RESUME_DEEP_DIVE = "RESUME_DEEP_DIVE"
    TECHNICAL_QA = "TECHNICAL_QA"
    TECHNICAL_EXERCISE = "TECHNICAL_EXERCISE"
    BEHAVIORAL = "BEHAVIORAL"
    WRAP_UP = "WRAP_UP"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TranscriptSpeaker(str, Enum):
    INTERVIEWER = "INTERVIEWER"
    CANDIDATE = "CANDIDATE"
    SYSTEM = "SYSTEM"


class InterviewStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CandidateRecommendation(str, Enum):
    STRONG_HIRE = "STRONG_HIRE"
    HIRE = "HIRE"
    LEAN_HIRE = "LEAN_HIRE"
    LEAN_REJECT = "LEAN_REJECT"
    REJECT = "REJECT"
    INCONCLUSIVE = "INCONCLUSIVE"


class AssessmentStatus(str, Enum):
    ASSESSED = "ASSESSED"
    NOT_ASSESSED = "NOT_ASSESSED"
    ATTEMPTED = "ATTEMPTED"


class QuestionType(str, Enum):
    INTRODUCTORY = "INTRODUCTORY"
    RESUME_DEEP_DIVE = "RESUME_DEEP_DIVE"
    PROJECT_DEEP_DIVE = "PROJECT_DEEP_DIVE"
    TECHNICAL_CONCEPT = "TECHNICAL_CONCEPT"
    IMPLEMENTATION = "IMPLEMENTATION"
    TRADEOFF = "TRADEOFF"
    DEBUGGING = "DEBUGGING"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    BEHAVIORAL = "BEHAVIORAL"
    EXPERIENCE = "EXPERIENCE"
    SCENARIO = "SCENARIO"
    CODING_DISCUSSION = "CODING_DISCUSSION"


class CodeLanguage(str, Enum):
    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    JAVA = "java"
    GO = "go"
    RUST = "rust"


class QuestionDifficulty(str, Enum):
    JUNIOR = "JUNIOR"
    MID = "MID"
    SENIOR = "SENIOR"
    LEAD = "LEAD"
    PRINCIPAL = "PRINCIPAL"


class TechnicalProblemType(str, Enum):
    CODE_REVIEW = "CODE_REVIEW"
    BUG_INVESTIGATION = "BUG_INVESTIGATION"
    DEBUGGING = "DEBUGGING"
    IMPLEMENTATION = "IMPLEMENTATION"
    PERFORMANCE = "PERFORMANCE"
    REFACTORING = "REFACTORING"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    ARCHITECTURE_REVIEW = "ARCHITECTURE_REVIEW"
    API_DESIGN = "API_DESIGN"
    CODEBASE_DISCUSSION = "CODEBASE_DISCUSSION"
    SECURITY_REVIEW = "SECURITY_REVIEW"
    DATA_STRUCTURES_AND_ALGORITHMS = "DATA_STRUCTURES_AND_ALGORITHMS"
    ALTERNATIVE_IMPLEMENTATION = "ALTERNATIVE_IMPLEMENTATION"


class ArtifactType(str, Enum):
    CODEBASE = "CODEBASE"
    CODE_SNIPPET = "CODE_SNIPPET"
    SYSTEM_DIAGRAM = "SYSTEM_DIAGRAM"
    ARCHITECTURE = "ARCHITECTURE"
    DATA_MODEL = "DATA_MODEL"
    EVALUATION_BLUEPRINT = "EVALUATION_BLUEPRINT"


class EvaluationIssueType(str, Enum):
    LOGIC_ERROR = "LOGIC_ERROR"
    STATE_INVARIANT_BREACH = "STATE_INVARIANT_BREACH"
    CONCURRENCY_HAZARD = "CONCURRENCY_HAZARD"
    DATA_FLOW_DEFECT = "DATA_FLOW_DEFECT"
    RESOURCE_LEAK = "RESOURCE_LEAK"
    ERROR_HANDLING_GAP = "ERROR_HANDLING_GAP"
    PERFORMANCE_BOTTLENECK = "PERFORMANCE_BOTTLENECK"
    SECURITY_VULNERABILITY = "SECURITY_VULNERABILITY"
    API_CONTRACT_VIOLATION = "API_CONTRACT_VIOLATION"
    ARCHITECTURAL_TRADEOFF = "ARCHITECTURAL_TRADEOFF"
